### ISSUE TITLE
Infinite loop when using double MonitorField from django-model-utils with defer()/only()

### ISSUE THREAD

**Issue by jdotjdot** [romgar/django-dirtyfields#94] opened 2016-11-02 07:09 UTC
We just upgraded to Django 1.10 and use `DirtyFieldsMixin` all over the place. After much debugging after finding an issue, we've noticed that when using `.only()` or `.defer()` with `.get()` on a model that subclasses `DirtyFieldsMixin`, you will end up in an infinite loop that maxes out with a maximum recursion error.

**Comment by romgar** [comment] 2016-11-09 19:53
Hi @jdotjdot,

Can you please write a test to show this issue?

**Comment by jdotjdot** [comment] 2016-11-10 04:25
It looks like this may be an odd conflict with `MonitorField` from [django-model-utils](https://github.com/carljm/django-model-utils).  I'm continuing to investigate.

**Comment by vannitotaro** [comment] 2016-11-11 12:28
Same problem here (Django 1.10).

Minimum test case:

`MyDirtyFieldsModel.objects.only('id').first()`

```
/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in first(self)
    554         Returns the first object of a query, returns None if no match is found.
    555         """
--> 556         objects = list((self if self.ordered else self.order_by('pk'))[:1])
    557         if objects:
    558             return objects[0]

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in __iter__(self)
    254                - Responsible for turning the rows into model objects.
    255         """
--> 256         self._fetch_all()
    257         return iter(self._result_cache)
    258 

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in _fetch_all(self)
   1085     def _fetch_all(self):
   1086         if self._result_cache is None:
-> 1087             self._result_cache = list(self.iterator())
   1088         if self._prefetch_related_lookups and not self._prefetch_done:
   1089             self._prefetch_related_objects()

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in __iter__(self)
     64         related_populators = get_related_populators(klass_info, select, db)
     65         for row in compiler.results_iter(results):
---> 66             obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
     67             if related_populators:
     68                 for rel_populator in related_populators:

/usr/local/lib/python2.7/dist-packages/django/db/models/base.pyc in from_db(cls, db, field_names, values)
    563             values.reverse()
    564             values = [values.pop() if f.attname in field_names else DEFERRED for f in cls._meta.concrete_fields]
--> 565         new = cls(*values)
    566         new._state.adding = False
    567         new._state.db = db

/usr/local/lib/python2.7/dist-packages/dirtyfields/dirtyfields.pyc in __init__(self, *args, **kwargs)
     25         if self.ENABLE_M2M_CHECK:
     26             self._connect_m2m_relations()
---> 27         reset_state(sender=self.__class__, instance=self)
     28 
     29     def _connect_m2m_relations(self):

/usr/local/lib/python2.7/dist-packages/dirtyfields/dirtyfields.pyc in reset_state(sender, instance, **kwargs)
    120     # original state should hold all possible dirty fields to avoid
    121     # getting a `KeyError` when checking if a field is dirty or not
--> 122     instance._original_state = instance._as_dict(check_relationship=True)
    123     if instance.ENABLE_M2M_CHECK:
    124         instance._original_m2m_state = instance._as_dict_m2m()

/usr/local/lib/python2.7/dist-packages/dirtyfields/dirtyfields.pyc in _as_dict(self, check_relationship, include_primary_key)
     48                 continue
     49 
---> 50             field_value = getattr(self, field.attname)
     51 
     52             # If current field value is an expression, we are not evaluating it

/usr/local/lib/python2.7/dist-packages/django/db/models/query_utils.pyc in __get__(self, instance, cls)
    113             val = self._check_parent_chain(instance, name)
    114             if val is None:
--> 115                 instance.refresh_from_db(fields=[self.field_name])
    116                 val = getattr(instance, self.field_name)
    117             data[self.field_name] = val

/usr/local/lib/python2.7/dist-packages/django/db/models/base.pyc in refresh_from_db(self, using, fields)
    683             db_instance_qs = db_instance_qs.only(*fields)
    684 
--> 685         db_instance = db_instance_qs.get()
    686         non_loaded_fields = db_instance.get_deferred_fields()
    687         for field in self._meta.concrete_fields:

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in get(self, *args, **kwargs)
    377         if self.query.can_filter() and not self.query.distinct_fields:
    378             clone = clone.order_by()
--> 379         num = len(clone)
    380         if num == 1:
    381             return clone._result_cache[0]

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in __len__(self)
    236 
    237     def __len__(self):
--> 238         self._fetch_all()
    239         return len(self._result_cache)
    240 

... last 10 frames repeated, from the frame below ...

/usr/local/lib/python2.7/dist-packages/django/db/models/query.pyc in _fetch_all(self)
   1085     def _fetch_all(self):
   1086         if self._result_cache is None:
-> 1087             self._result_cache = list(self.iterator())
   1088         if self._prefetch_related_lookups and not self._prefetch_done:
   1089             self._prefetch_related_objects()
```

`RuntimeError: maximum recursion depth exceeded`

**Comment by jdotjdot** [comment] 2016-11-11 15:02
@vannitotaro  you rock--so it's not just me. I reproduce it every time in our codebase, but so far I have not been able to properly write a failing test. It's very odd.

**Comment by romgar** [comment] 2016-11-12 23:20
Sounds a regression of #22 :'(

Some tests have been written to cover it. Seems not enough.

@vannitotaro can you give more context? The definition of `MyDirtyFieldsModel`? In which context are you calling this `only`?

If you could write a test to reproduce it, it would help me to fix it (I have tried a basic model and `only` call, but can't reproduce this recursive error...).

**Comment by vannitotaro** [comment] 2016-11-13 10:29
Hi @romgar, first of all thank you for your time! I'll try to write a minimum test case - I thought it was already a valid one, but as per your tests the issue seems bound to specific model definitions. In the meantime I'll give you some context about the error I get in production.

Running `MyDirtyFieldsModel.objects.only('id').first()` - where `MyDirtyFieldsModel` is a bug-report placeholder for one of my two models which inherits from DirtyFieldsMixin - from a `manage.py shell` ipython session gives `RuntimeError: maximum recursion depth exceeded`.

The first model has these kind of fields: ForeignKey, CharField, DateTimeField, DecimalField, IntegerField, PositiveSmallIntegerField, BooleanField.

The second model has these kind of fields: CharField, ForeignKey, DateField, DecimalField, IntegerField, BooleanField, NullBooleanField, PositiveSmallIntegerField.

The second model has two ForeignKey pointing to the first model.

Both models redefine `__unicode__()` using some fields to format the instance description.

I'll dig more asap. Thank you!

**Comment by romgar** [comment] 2016-11-13 15:03
Can you copy/paste your 2 models?

Issue #84 was raised involving 2 `ForeignKey` and deferred fields. It fixed the situation described in the test written in the corresponding MR, but you probably have another use case :-)

**Comment by vannitotaro** [comment] 2016-11-13 23:56
@romgar unfortunately I cannot share production code. Anyway I applied `DirtyFieldsMixin` to all my models: **the recursion error is always raised if there are two or more `ForeignKey`s**.

I've a model with only two fields, both ForeignKey, and the exception is raised. Adapted code:

```
class Model3(DirtyFieldsMixin, models.Model):
    model1 = models.ForeignKey(Model1, on_delete=models.CASCADE)
    model2 = models.ForeignKey(Model2, on_delete=models.CASCADE)
```

I see **two differences** between the issue #84 test (https://github.com/romgar/django-dirtyfields/blob/develop/tests/models.py#L110) and my test case:

1. my model has foreign keys pointing to different models, not the same one;
2. my model fields do not set `null=True`.

**Comment by jdotjdot** [comment] 2016-11-13 23:58
Interesting.  My models also definitely have >1 foreign key.

**Comment by vannitotaro** [comment] 2016-11-15 09:34
Just tried my testcase on a standalone run of django-dirtyfields tox and no RuntimeError is raised... I'll try to understand what's missing to trigger the exception.

**Comment by vannitotaro** [comment] 2016-11-15 10:36
@romgar @jdotjdot after debugging in production, I discovered what have been already discovered, i.e. that this bug is the same as issue #84 and already solved by PR #85.

**The remaining bug here is that `django-dirtyfields` package on PyPI shoud be updated asap for all the people using `pip` to install it.** 🤓

Thank you! 👍

**Comment by vannitotaro** [comment] 2016-11-15 15:07
@jdotjdot could you try installing `django-dirtyfields` latest version from sources to see if your exceptions go away too so that @romgar may close this issue?

**Comment by romgar** [comment] 2016-11-15 23:51
Sorry about that @vannitotaro... I thought I released a new version few time ago. Thanks for investigating!

I will release a new version tomorrow!

**Comment by jdotjdot** [comment] 2016-11-16 19:01
@romgar Thanks so much! Let us know when you release!  We've been eagerly watching the repo for its release to PyPi since it's been causing us problems.

I will try to test the latest version as well if this isn't released before then.

**Comment by romgar** [comment] 2016-11-16 23:00
@vannitotaro @jdotjdot Version `1.2.1` is live and available on pypi. Please check with this version!

**Comment by jdotjdot** [comment] 2016-11-16 23:09
No, I'm still having the issue, unfortunately.

**Comment by jdotjdot** [comment] 2016-11-16 23:14
Actually--it appears I only am having the issue on models with `MonitorField` from django-model-utils.

**Comment by romgar** [comment] 2016-11-16 23:29
@jdotjdot I have tried to create a test with a model containing a `MonitorField`, and I still can't reproduce your issue.
If you could write a test that fails with this latest version of `django-dirtyfields`, I could probably help you more to fix this issue.

**Comment by romgar** [comment] 2016-11-16 23:31
Which version of `django-model-utils` are you using?

**Comment by jdotjdot** [comment] 2016-11-17 00:40
I *finally* managed to write a failing test!

https://travis-ci.org/jdotjdot/django-dirtyfields/jobs/176563994

**Comment by vannitotaro** [comment] 2016-11-17 08:59
@romgar I've just tried: I can confirm v1.2.1 on PyPI solved _my_ issue, not @jdotjdot's one. Maybe it would be better now to change issue title to add a reference to MonitorField somewhere.

**Comment by romgar** [comment] 2016-11-17 10:02
@vannitotaro good news! I will update the issue title after I'm sure that's related only to `MonitorField`.

**Comment by romgar** [comment] 2016-11-17 23:17
I have simplified your test @jdotjdot and found it passing with `TestMonitorFieldModel` but not with`TestDoubleMonitorFieldModel`:

```   
TestDoubleMonitorFieldModel.objects.create()
results = list(TestDoubleMonitorFieldModel.objects.only('id'))
```
Error reproduced, time to work! :-)

**Comment by romgar** [comment] 2016-11-17 23:44
And it seems that using only one `MonitorField` in a model is not triggering the recursion error. Only from 2+...

**Comment by jdotjdot** [comment] 2016-11-17 23:46
Interesting--but in that case, how come the `TestMonitorFieldModel` in my branch was still failing despite only one `MonitorField`?

**Comment by romgar** [comment] 2016-11-18 00:06
I also tried without inheriting from `DirtyFieldsMixin` and I get the same recursion error. It is maybe not related to `django-dirtyfields`.

Can you try to not inherit from `DirtyFieldsMixin` in your models to see if you still have this issue?

**Comment by romgar** [comment] 2016-11-18 00:28
I managed to reproduce the issue in `django-model-utils` project: https://github.com/carljm/django-model-utils/issues/241

**Comment by romgar** [comment] 2016-11-20 14:35
@jdotjdot closing this issue, as it seems to be not related to `django-dirtyfields`. Currently proposing a patch to solve this issue on `django-model-utils`.

Feel free to reopen it if you think your issue is still related to `django-dirtyfields`.

**Closed by romgar** 2016-11-20 14:35 UTC
